### PR TITLE
MKL: conv: remove unused headers

### PR DESCRIPTION
**Pull request by rsdubtso**

### CODE REVIEW

**Comment by sharannarang** [comment]
@rsdubtso , could you please also remove these files? 

https://github.com/baidu-research/DeepBench/blob/master/code/intel/gemm/input.h
https://github.com/baidu-research/DeepBench/blob/master/code/intel/sgemm/input.h

I think these files are still being used. It'll be great if you could update the code and get rid of them. Thanks!

**Comment by rsdubtso** [comment]
Sure, will look into this.

**Comment by efeguney** [comment]
@rsdubtso @sharannarang , I will update the GEMM code and share common header files. In addition, sgemm folder can be removed now.

**Comment by efeguney** [comment]
@sharannarang , PR#61 removes input.h dependency from Intel GEMM components.

**Comment by sharannarang** [comment]
Thanks @rsdubtso and @efeguney . Merging this PR.

**Pull request merged**
