### PR TITLE
Add cuDNNv6 results for 1080Ti and TitanXp.

### PR DESCRIPTION
**Pull request by bryancatanzaro**
Added recent results for GTX1080Ti and TitanXp.

### CODE REVIEW

**Comment by sharannarang** [comment]
@bryancatanzaro , Thanks for contributing these results!

Some small comments regarding the format:

- Can you split the results in two separate excel sheets? We've been creating a separate excel sheet for each processor and would be nice to keep it consistent. 
- Could you also add a `specs` worksheet in each excel book? It includes detailed specifications of the software and hardware configuration. Please look at one of the other results file for an example. 
- Can you update the Vanilla RNN results to mention 50 timesteps instead of 25? The benchmark script prints out 25 timesteps, even though it runs the RNN for 50 timesteps. I'll create a PR later today to fix this.
- Do you think you can add the `all_reduce` results? I'm guessing they won't be different from the TitanX maxwell results. So, not a big deal if it's too much work.

**Comment by bryancatanzaro** [comment]
Thanks @sharannarang! I'll send in an updated pull request with 2 separate excel sheets containing the revisions you requested. The `all_reduce` results should be the same as the TitanX Maxwell results, so I think we'll leave them out if that's ok.

**Comment by bryancatanzaro** [comment]
@sharannarang I've made the changes you requested. Just to make sure we're agreeing here: by moving from 25 to 50 timesteps for the Vanilla RNN results, reported TFlops go up by 2X. They still look reasonable, so this is probably correct if you've found an error in the script. But just wanted to make sure that's what you were expecting.

**Comment by sharannarang** [comment]
Thanks @bryancatanzaro . The changes look good.

Regarding the RNN timesteps, the benchmark always prints 25 timesteps here: 

https://github.com/baidu-research/DeepBench/blob/master/code/nvidia/rnn_bench.cu#L303

RNN kernels have been specified with 50 timesteps in the problem set, so it's just a printing error. As you mentioned the reported TFlops look reasonable. 

I'll merge this PR.

**Pull request merged**
