### PR TITLE
Updating result files for P100, TitanXP & 1080Ti 

### PR DESCRIPTION
**Pull request by dibasc**
[DeepBench_NV_1080Ti.xlsx](https://github.com/baidu-research/DeepBench/files/1201677/DeepBench_NV_1080Ti.xlsx)
[DeepBench_NV_P100.xlsx](https://github.com/baidu-research/DeepBench/files/1201679/DeepBench_NV_P100.xlsx)
[DeepBench_NV_TitanXp.xlsx](https://github.com/baidu-research/DeepBench/files/1201678/DeepBench_NV_TitanXp.xlsx)

### CODE REVIEW

**Comment by sharannarang** [comment]
@dibasc , Thanks for submitting results to DeepBench. Happy to accept these results but I'd request a couple of changes:

1. Can you rename the files to follow the standard format? P100 results would be `DeepBench_NV_P100.xlxs`. We don't include the CUDA version or Trg keyword in the filename. We only include one results file per processor to avoid confusion. So, these results would replace the existing results file in the `results/train` directory. 
2. Can you confirm the precision for `Fp16` sheet in the P100 results spreadsheet? Currently, the precision is mentioned as `Float`. 
3. The All reduce results are missing from the P100 results. You don't need to rerun them. You can simply copy them from the existing `DeepBench_NV_P100.xlxs` file since this change doesn't impact the all reduce results. 
4. It would be great if you can include results on the TitanX Pascal as well. It would keep all the Pascal processors results at the same CUDA and cudNN versions.

**Comment by dibasc** [comment]
[DeepBench_NV_1080Ti.xlsx](https://github.com/baidu-research/DeepBench/files/1201317/DeepBench_NV_1080Ti.xlsx)
[DeepBench_NV_P100.xlsx](https://github.com/baidu-research/DeepBench/files/1201316/DeepBench_NV_P100.xlsx)
[DeepBench_NV_TitanXp.xlsx](https://github.com/baidu-research/DeepBench/files/1201318/DeepBench_NV_TitanXp.xlsx)

Renamed the files to the correct format.  Also, included description for P100 FP16 sheet to match.  Will upload the TitanX Pascal data when I have it ready.

**Comment by sharannarang** [comment]
Could you update the PR as well? The PR still shows three additional files. Instead, you can replace the existing files in the repo.

**Comment by sharannarang** [comment]
LGTM, merging

**Pull request merged**
