### PR TITLE
Fix builds with default RHEL / Fedora / CentOS OpenMPI packages

### LINKED ISSUE #81: Make DeepBench compile cleanly with provided libs on RHEL
The DeepBench makefiles assume certain libs and header files (e.g. libmpi) are located in the same directory tree.  For reasons I have yet to discern RHEL installs the libraries in one directory structure and the headers in another (in the -devel packages).  By applying the below patch and adding "MPI_INCLUDE_PATH=/usr/include/openmpi-x86_64" DeepBench now builds cleanly on RHEL; I've coded the change such that it shouldn't require any changes for systems that have libraries and header files in the same directory.

---

diff -ur DeepBench.orig/code/baidu_allreduce/Makefile DeepBench/code/baidu_allreduce/Makefile
--- DeepBench.orig/code/baidu_allreduce/Makefile	2017-12-14 14:53:03.255428367 -0500
+++ DeepBench/code/baidu_allreduce/Makefile	2017-12-12 12:15:19.396655494 -0500
@@ -6,6 +6,7 @@
 CUDA_PATH?=/usr/local/cuda
 CUDA_LIB64=$(CUDA_PATH)/lib64
 MPI_PATH?=/usr/local/openmpi
+MPI_INCLUDE_PATH?=/usr/local/openmpi
 BAIDU_ALLREDUCE_PATH?=/local/baidu-allreduce
 BIN_DIR?=bin
 MKDIR=mkdir -p
@@ -21,8 +22,8 @@
 
 ring_all_reduce:
 	$(MKDIR) $(BIN_DIR)
-	$(MPI_PATH)/bin/$(CC) -c -std=c++11 -I $(MPI_PATH)/include -I $(BAIDU_ALLREDUCE_PATH) -I $(CUDA_PATH)/include -I $(KERNELS_DIR) -DOMPI_SKIP_MPICXX= ring_all_reduce_mpi.cpp -o $(BIN_DIR)/ring_all_reduce_mpi.o
-	$(CUDA_PATH)/bin/$(NVCC) -c -std=c++11 -I $(MPI_PATH)/include -I $(BAIDU_ALLREDUCE_PATH) -I $(CUDA_PATH)/include -DOMPI_SKIP_MPICXX= $(BAIDU_ALLREDUCE_PATH)/collectives.cu -o $(BIN_DIR)/collectives.o
+	$(MPI_PATH)/bin/$(CC) -c -std=c++11 -I $(MPI_INCLUDE_PATH) -I $(BAIDU_ALLREDUCE_PATH) -I $(CUDA_PATH)/include -I $(KERNELS_DIR) -DOMPI_SKIP_MPICXX= ring_all_reduce_mpi.cpp -o $(BIN_DIR)/ring_all_reduce_mpi.o
+	$(CUDA_PATH)/bin/$(NVCC) -c -std=c++11 -I $(MPI_INCLUDE_PATH) -I $(BAIDU_ALLREDUCE_PATH) -I $(CUDA_PATH)/include -DOMPI_SKIP_MPICXX= $(BAIDU_ALLREDUCE_PATH)/collectives.cu -o $(BIN_DIR)/collectives.o
 	$(MPI_PATH)/bin/$(CC) -o $(BIN_DIR)/ring_all_reduce $(BIN_DIR)/ring_all_reduce_mpi.o $(BIN_DIR)/collectives.o -L$(CUDA_PATH)/lib64 -L$(MPI_PATH)/lib -lcudart -lmpi -DOMPI_SKIP_MPICXX=
 
 clean:
diff -ur DeepBench.orig/code/nvidia/Makefile DeepBench/code/nvidia/Makefile
--- DeepBench.orig/code/nvidia/Makefile	2017-12-14 14:53:03.257428373 -0500
+++ DeepBench/code/nvidia/Makefile	2017-12-12 11:49:20.379360097 -0500
@@ -7,6 +7,7 @@
 CUDNN_PATH?=/usr/local/cudnn
 NCCL_PATH?=/usr/local/nccl
 MPI_PATH?=/usr/local/openmpi
+MPI_INCLUDE_PATH?=/usr/include/openmpi
 BIN_DIR?=bin
 MKDIR=mkdir -p
 #BLAS
@@ -45,7 +46,7 @@
 
 nccl_mpi:
 	$(MKDIR) $(BIN_DIR)
-	$(CUDA_PATH)/bin/$(NVCC) nccl_mpi_all_reduce.cu -o $(BIN_DIR)/nccl_mpi_all_reduce -I $(KERNELS_DIR) -I $(NCCL_PATH)/include/ -I $(CUDNN_PATH)/include/ -I $(MPI_PATH)/include -L $(NCCL_PATH)/lib/ -L $(CUDNN_PATH)/lib64 -L $(MPI_PATH)/lib -lnccl -lcurand -lcudart -lmpi $(NVCC_ARCH_ARGS) -std=c++11 
+	$(CUDA_PATH)/bin/$(NVCC) nccl_mpi_all_reduce.cu -o $(BIN_DIR)/nccl_mpi_all_reduce -I $(KERNELS_DIR) -I $(NCCL_PATH)/include/ -I $(CUDNN_PATH)/include/ -I $(MPI_INCLUDE_PATH) -L $(NCCL_PATH)/lib/ -L $(CUDNN_PATH)/lib64 -L $(MPI_PATH)/lib -lnccl -lcurand -lcudart -lmpi $(NVCC_ARCH_ARGS) -std=c++11 
 
 sparse:
 	$(MKDIR) $(BIN_DIR) 
diff -ur DeepBench.orig/code/osu_allreduce/Makefile DeepBench/code/osu_allreduce/Makefile
--- DeepBench.orig/code/osu_allreduce/Makefile	2017-12-14 14:53:03.258428376 -0500
+++ DeepBench/code/osu_allreduce/Makefile	2017-12-12 11:51:07.655654032 -0500
@@ -3,6 +3,7 @@
 CC_FLAGS= -c -O2 -pthread -Wall -march=native
 
 MPI_PATH?=/usr/local/openmpi
+MPI_INCLUDE_PATH?=/usr/local/openmpi
 CUDA_PATH?=/usr/local/cuda
 MKDIR=mkdir -p
 BIN_DIR?=bin
@@ -17,10 +18,10 @@
 
 coll:
 	$(MKDIR) $(BIN_DIR)
-	$(CC) -o $(BIN_DIR)/osu_coll.o $(CC_FLAGS) -I$(CUDA_PATH)/include -I$(MPI_PATH)/include  osu_coll.c
+	$(CC) -o $(BIN_DIR)/osu_coll.o $(CC_FLAGS) -I$(CUDA_PATH)/include -I$(MPI_INCLUDE_PATH) osu_coll.c
 
 allreduce:
-	$(CC) -o $(BIN_DIR)/osu_allreduce.o $(CC_FLAGS) -I $(KERNELS_DIR) -I$(CUDA_PATH)/include -I$(MPI_PATH)/include osu_allreduce.c
+	$(CC) -o $(BIN_DIR)/osu_allreduce.o $(CC_FLAGS) -I $(KERNELS_DIR) -I$(CUDA_PATH)/include -I$(MPI_INCLUDE_PATH) osu_allreduce.c
 
 clean:
 	rm -rf $(BIN_DIR)

### PR DESCRIPTION
**Pull request by frival**
By default RHEL / Fedora / CentOS split OpenMPI libraries and headers into the openmpi and openmpi-devel packages, each of these installs to a different directory.  The current Makefiles assume headers and libraries are in the same directory structure.  Create a separate MPI_INCLUDE_PATH Makefile variable for the include path, default it to MPI_PATH so it should "just work" for other platforms or systems where the user has built and installed OpenMPI from source.

Closes #81

### CODE REVIEW

**Comment by mpatwary** [comment]
Thanks @frival , The changes look good to me. @sharannarang Please cross check and merge. Thanks All.

**Comment by sharannarang** [comment]
@frival , thanks for this PR. As discussed in #81, are you planing to update the README as well as a part of this PR ?

**Comment by frival** [comment]
Yes, I should be posting an update shortly.  I had several conflicts to deal with yesterday but should have time to finish this up today.

**Comment by frival** [comment]
I'm unclear as to where you want things changed - code/baidu_allreduce/Makefile is already updated and I don't see a README.md or the like anywhere else I might be updating.  What am I missing?

**Comment by mpatwary** [comment]
I was basically mentioning the README.md. The changes you made in the README.md is only on the NVIDIA Benchmarks compiling section, I was thinking to do the same for the Baidu Benchmarks section.

**Comment by frival** [comment]
Ouch, brain cramp.  I see what you mean, I'll take care of that right now.

**Comment by sharannarang** [comment]
Thanks for these changes! Merging.

**Pull request merged**
