### PR TITLE
Fix filter dimensions typo in excel sheets

### LINKED ISSUE #42: Typo in convolution configs?
Hi,
Looks like there is a typo in spreadsheets:
image

Output of the first DeepSpeech convolution does not fit the second layer:
out_W = (W + 2 * pad_w - filter_w + 1) / stride_w = (700 + 0 - 5 + 1) / 2 = 348
out_H = (H + 2 * pad_h - filter_h + 1) / stride_h = (161 + 0 - 20 + 1) / 2 = 71

I guess R should be filter height and S should be filter width. In that case DeepSpeech layers fit perfectly:
out_W = (700 + 0 - 20 + 1) / 2 = 341
out_H = (161 + 0 - 5 + 1) / 2 = 79

Please also chech KWS case for the same issue.

### PR DESCRIPTION
**Pull request by sharannarang**
Fixes #42.

### CODE REVIEW

**Comment by Kirpich30000** [comment]
DeepSpeech looks good, but KWS became weird (I guess it was added with previous labels in mind). It should be:

Source | W (input - time) | H (input) | C (channels) | N (batch size) | K  (number of filters) | R (filter height) | S (filter width) | pad_h | pad_w | Vertical Stride | Horizontal Stride
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
KWS | 151 | 40 | 1 | 1 | 32 | **5** | **20** | 8 | 8 | 2 | 8

**Comment by Kirpich30000** [comment]
Wow, I take a look at the code and found that it messed up:
spreadsheets do not fit conv_problems.h
different implementations read parameters inconsistently

I propose to always specify horisontal spatial parameter first. That way table became more consistent and less error prone:

Source | W (input - time) | H (input) | C (channels) | N (batch size) | K 
  (number of filters) | S (filter width) | R (filter height) | pad_w | pad_h | Horizontal Stride | Vertical Stride
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
DeepSpeech | 700 | 161 | 1 | 1 | 32 | 20 | 5 | 0 | 0 | 2 | 2
DeepSpeech | 700 | 161 | 1 | 2 | 32 | 20 | 5 | 0 | 0 | 2 | 2
DeepSpeech | 700 | 161 | 1 | 4 | 32 | 20 | 5 | 0 | 0 | 2 | 2
DeepSpeech | 341 | 79 | 32 | 1 | 32 | 10 | 5 | 0 | 0 | 2 | 2
DeepSpeech | 341 | 79 | 32 | 2 | 32 | 10 | 5 | 0 | 0 | 2 | 2
DeepSpeech | 341 | 79 | 32 | 4 | 32 | 10 | 5 | 0 | 0 | 2 | 2
KWS | 151 | 40 | 1 | 1 | 32 | 20 | 5 | 8 | 8 | 8 | 2

Also the same sequence of parameters should be used for both spreadsheets and header files.

**Comment by sharannarang** [comment]
@Kirpich30000 , thanks for looking into this. I think the problem is limited to the ARM convolution code where `R` is used as the filter width. This doesn't impact any of the results since ARM convolutions only support square filters. 

You're right about the KWS kernel. I'll update it in the spreadsheet. 

Additionally, I agree regarding your proposed format. #53 updates the code but not the spreadsheets. I can do it as a part of this PR.

**Comment by Kirpich30000** [comment]
@sharannarang note that the KWS kernel in conv_problems.h also have bug with stride - wstride should be 8 and hstride is 2.

>  #53 updates the code but not the spreadsheets. I can do it as a part of this PR.

I'm totaly fine if you do all changes as a part of this PR.

**Comment by sharannarang** [comment]
Alright, all the code updates and changes to excel files are now part of this PR. The KWS kernel is also updated and results in a segmentation fault. So, I've left it commented out. 

Thanks for looking into this @Kirpich30000 . Can you look over this briefly to make sure I've covered everything we discussed?

**Comment by Kirpich30000** [comment]
I've eyeballed some spreadsheets with results and spotted few more things:
- P, Q params not always follow "width first" rule
- For RaspberryPI formulas for P and Q are mixes w and h in same formula
- Formulas for P and Q are not precise:
   - Result is not rounded which affects teraflops calculation
   - Cells are formated to show only integer part. Still resulted format will not always show correct value
   - Correct formula for symmetric padding is: outputDim = 1 + (inputDim - filterDim + 2 * pad) / stride, where result of division is rounded down.

**Comment by sharannarang** [comment]
@Kirpich30000 , I've updated the spreadsheets to reflect the correct formulas for output height and width calculations and the ordering issue as well.

**Comment by Kirpich30000** [comment]
Looks good to me

**Pull request merged**
