### PR TITLE
Fix a bug on mkl timeit

### PR DESCRIPTION
**Pull request by etaf**

### CODE REVIEW

**Comment by sharannarang** [comment]
@rsdubtso , can you review this change?

**Comment by dmudiger** [comment]
LGTM

**Comment by rsdubtso** [comment]
I missed this and I don't think it looks good to me... the 'if' there was to reduce the number of kernel calls when a problem is large or a kernel is slow.

**Comment by etaf** [comment]
@rsdubtso 
It was already been done in 'for (; iters_done < niters && result.avg_ms < max_ms_total; iters_done++) '

**Comment by rsdubtso** [comment]
Oh. Thanks. Makes sense.

**Pull request merged**
